# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
   desc "Build"
   lane :build do
     gradle(task: "clean assembleRelease")
   end

    lane :production do
     gradle(task: "clean assembleRelease")

       gradle(
         task: 'bundle',
         build_type: 'Release',
         print_command: false,

       )
       upload_to_play_store(
         track: 'production',
                skip_upload_apk: true
                          )
       end
end
